import time

from motion_helper_functions import *

X = 0

def discard_blade():
    # change_gripping_angle_to(15)
    # time.sleep(1)
    # move_Y_gantry_to(174)
    # time.sleep(1)
    move_X_gantry_to(42)
    time.sleep(1)
    move_blade_to(0)
    time.sleep(2)
    move_Y_gantry_to(174)
    time.sleep(1)
    move_blade_to(43)
    time.sleep(5)
    # change_gripping_angle_to(15)
    # time.sleep(5)
    grab_blade()
    time.sleep(1)
    # unlock_pressure_plate()
    time.sleep(1)
    move_blade_at_2d_plane(159, 30.5)
    time.sleep(4)
    # change_gripping_angle_to(110)
    # time.sleep(2)
    # change_gripping_angle_to(90)
    # time.sleep(6)
    move_Y_gantry_to(28)
    time.sleep(2)
    #release_blade()
    #time.sleep(1)
    move_blade_to(60)
def home_all():
    home_gantry_Y()
    home_vertical_gantry()
    home_gantry_X()

def new_blade():
    # unlock_pressure_plate()
    time.sleep(1)
    change_gripping_angle_to(100)
    time.sleep(1)
    change_gripping_angle_to(90)
    time.sleep(1)
    move_blade_to(50)
    time.sleep(1)
    move_X_gantry_to(70)
    time.sleep(1)
    move_Y_gantry_to(28)
    time.sleep(1)
    move_blade_to(73.5)
    time.sleep(1)
    grab_blade()
    time.sleep(2)
    # move_blade_at_2d_plane(154,28.5)
    move_blade_to(30.5)
    time.sleep(1)
    move_Y_gantry_to(159)
    time.sleep(5)
    change_gripping_angle_to(15)
    time.sleep(4)
    move_blade_at_2d_plane(187, 51)
    time.sleep(8)
    move_blade_backward_by(6)
    time.sleep(3)
    # lock_pressure_plate()
    time.sleep(2)
    release_blade()
    time.sleep(4)
    change_gripping_angle_to(100)
    time.sleep(5)
    # unlock_pressure_plate()
    time.sleep(1)
    # lock_pressure_plate()


def move_blade_to_mid_position():
    change_gripping_angle_to(15)
    time.sleep(2)
    grab_blade()
    time.sleep(2)
    # unlock_pressure_plate()
    time.sleep(3)
    move_X_gantry_to(70)
    time.sleep(2)
    grab_blade()
    time.sleep(2)
    # lock_pressure_plate()
    time.sleep(2)
    release_blade()
    time.sleep(2)
    change_gripping_angle_to(105)
    time.sleep(3)
    # unlock_pressure_plate()
    time.sleep(3)
    # lock_pressure_plate()
    time.sleep(3)

def process():
    while(True):
        move_blade_to_right_side()
        time.sleep(2)
        move_blade_to_mid_position()
        time.sleep(2)
        discard_blade()
        time.sleep(2)
        new_blade()
        time.sleep(2)
        move_blade_to_left_side()
        time.sleep(2)
        discard_blade()
        time.sleep(2)
        move_blade_to_mid_position()
        time.sleep(2)
        discard_blade()
        time.sleep(2)
        new_blade()
        time.sleep(2)


def move_blade_to_left_side():
    move_X_gantry_to(70)
    time.sleep(2)
    move_Y_gantry_to(174)
    time.sleep(3)
    move_blade_to(51)
    time.sleep(2)
    change_gripping_angle_to(105)
    time.sleep(1)

    change_gripping_angle_to(15)
    time.sleep(3)
    grab_blade() ##
    time.sleep(2)
    # unlock_pressure_plate()
    time.sleep(2)
    move_X_gantry_to(88)
    time.sleep(2)
    # lock_pressure_plate()
    time.sleep(2)
    release_blade()
    time.sleep(2)
    # lock_pressure_plate()
    time.sleep(2)
    change_gripping_angle_to(100)
    time.sleep(3)
    # unlock_pressure_plate()
    time.sleep(3)
    # lock_pressure_plate()
    time.sleep(3)

def move_blade_to_right_side():
    move_X_gantry_to(70)
    time.sleep(2)
    move_Y_gantry_to(174)
    time.sleep(2)
    move_blade_to(51)
    time.sleep(2)
    change_gripping_angle_to(105)
    time.sleep(1)

    change_gripping_angle_to(15)
    time.sleep(3)
    grab_blade()  ##
    time.sleep(2)
    # unlock_pressure_plate()
    time.sleep(2)
    move_X_gantry_to(60)
    time.sleep(2)
    # lock_pressure_plate()
    time.sleep(2)
    release_blade()
    time.sleep(2)
    change_gripping_angle_to(100)
    time.sleep(2)
    # lock_pressure_plate()
    time.sleep(3)
    # unlock_pressure_plate()
    time.sleep(3)
    # lock_pressure_plate()
    time.sleep(3)
